import { Geist, Geist_Mono, Poppins } from "next/font/google";
import "./globals.css";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

const poppins = Poppins({
  // variable: "--font-Poppins",
  // subsets: ["latin"],
  weight: ["100", "200", "400", "600", "700", "800", "900"],
});

export const metadata = {
  title: "Keretas Agency",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        // className={`${geistSans.variable} ${geistMono.variable} ${poppins.variable} antialiased`}
        className={`${poppins.className} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
